### ISSUE TITLE
SqliteError: no such table: undefined at return this[cppdb].prepare(sql, this, false);

### ISSUE THREAD

**Issue by ken-vat** [fukuball/rarity-analyser#10]
The rarity app is running fine on localhost. this script is failing. 

rarity-analyser-main$ yarn rarity-output-json
yarn run v1.22.17
$ node ./cmd/rarity_output_json.js
Process punk: #1

/mnt/c/Users/family/rarity-tool-git/rarity-analyser-main/node_modules/better-sqlite3/lib/methods/wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                           ^
SqliteError: no such table: undefined
    at Database.prepare (/mnt/c/Users/family/rarity-tool-git/rarity-analyser-main/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Object.exports.punk (/mnt/c/Users/family/rarity-tool-git/rarity-analyser-main/modules/jsondata.js:18:22)
    at /mnt/c/Users/family/rarity-tool-git/rarity-analyser-main/cmd/rarity_output_json.js:33:46       
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/mnt/c/Users/family/rarity-tool-git/rarity-analyser-main/cmd/rarity_output_json.js:28:7)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rarity-analyser-main$

**Comment by shreekalidass07** [comment]
facing the same issue, anything solutions?
